name: Hypervel Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  hypervel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: testing
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, exif, iconv
          tools: composer:v2
      
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Copy .env
        run: cp .env.example .env
      
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      
      - name: Generate key
        run: php artisan key:generate
      
      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache
      
      - name: Configure SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/database/database.sqlite" >> .env
      
      - name: Run migrations
        run: php artisan migrate
      
      - name: Install Node dependencies
        run: npm ci
      
      - name: Build assets
        run: npm run build
      
      - name: Run Hypervel tests
        env:
          SKIP_PERFORMANCE_TESTS: true
        run: vendor/bin/phpunit --testsuite Hypervel

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            storage/logs/laravel.log
            ./build/coverage-report 